### ISSUE TITLE
'formats' in configuration

### ISSUE THREAD

**Issue by arax** [CESNET/comfy#5]
What is this [1] option doing?

[1] https://github.com/CESNET/comfy/blob/master/config/comfy.yml#L6

**Comment by Misenko** [comment]
It says which formats of virtual machines/images will be build. You can choose either qemu (qcow2 image) or virtualbox (ova image) or both. It's mentioned in the README, must have slipped out of the configuration file.

**Comment by arax** [comment]
Ok.
