### ISSUE TITLE
configurable path to packer binaries

### ISSUE THREAD

**Issue by arax** [CESNET/comfy#6]
I need a configurable path to packer binaries (not just automated PATH lookup on exec). Is this [1] the only place where packer (or any other external tool) is executed?

[1] https://github.com/CESNET/comfy/blob/master/lib/comfy/creator.rb#L71

**Comment by Misenko** [comment]
Yes, it is. Do you want me to add it as an option in configuration file?

**Comment by arax** [comment]
Yes, please.
